function(find_highest_cuda_version OUT_INCLUDE_DIR OUT_LIB_DIR OUT_VERSION MIN_VERSION MAX_VERSION)
    set(CUDA_TOOLKIT_ROOT "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA")
    file(GLOB CUDA_VERSION_DIRS RELATIVE "${CUDA_TOOLKIT_ROOT}" "${CUDA_TOOLKIT_ROOT}/v*")

    set(HIGHEST_VERSION "")
    set(HIGHEST_VERSION_DIR "")
    foreach(DIR ${CUDA_VERSION_DIRS})
        string(REGEX REPLACE "^v" "" VERSION_NUMBER "${DIR}")
        if((MIN_VERSION STREQUAL "" OR VERSION_NUMBER VERSION_GREATER_EQUAL MIN_VERSION)
            AND (MAX_VERSION STREQUAL "" OR VERSION_NUMBER VERSION_LESS_EQUAL MAX_VERSION))
            if(HIGHEST_VERSION STREQUAL "" OR VERSION_NUMBER VERSION_GREATER HIGHEST_VERSION)
                set(HIGHEST_VERSION "${VERSION_NUMBER}")
                set(HIGHEST_VERSION_DIR "${DIR}")
            endif()
        endif()
    endforeach()

    if(HIGHEST_VERSION STREQUAL "")
        message(FATAL_ERROR "No CUDA Toolkit installation found in ${CUDA_TOOLKIT_ROOT} within range v${MIN_VERSION} - v${MAX_VERSION}")
    else()
        set(CUDA_INCLUDE_DIR "${CUDA_TOOLKIT_ROOT}/${HIGHEST_VERSION_DIR}/include")
        set(CUDA_LIB_DIR "${CUDA_TOOLKIT_ROOT}/${HIGHEST_VERSION_DIR}/lib/x64")
        set(${OUT_INCLUDE_DIR} "${CUDA_INCLUDE_DIR}" PARENT_SCOPE)
        set(${OUT_LIB_DIR} "${CUDA_LIB_DIR}" PARENT_SCOPE)
        set(${OUT_VERSION} "${HIGHEST_VERSION}" PARENT_SCOPE)
        message(STATUS "Found CUDA version v${HIGHEST_VERSION} at ${CUDA_TOOLKIT_ROOT}/${HIGHEST_VERSION_DIR}")
    endif()
endfunction()